services:
  mongodb:
    image: mongo:7
    container_name: categories-game-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: categories-game
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: categories-game-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
